# Этот конфиг можно использовать для перегрузки параметров докера с высшим приоритетом не зависимо от окружения.
# Для этого нужно скопировать этот файл в корень проекта. Он прописан в .gitignore по этому в репу не пападёт.
version: '3.9'

services:
   db:
       ports:
           - '127.0.0.1:3361:3306'
