"""add created at

Revision ID: 47b75eb093b1
Revises: 0b62a2a9a14c
Create Date: 2023-04-25 15:46:56.047357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b75eb093b1'
down_revision = '0b62a2a9a14c'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('offer', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'created_at')
    op.drop_column('category', 'created_at')
    # ### end Alembic commands ###
