"""user is_enabled

Revision ID: a31d4aad2367
Revises: 853c5adc9aa3
Create Date: 2023-02-14 18:34:37.330040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31d4aad2367'
down_revision = '853c5adc9aa3'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_enabled', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_is_enabled'), 'user', ['is_enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_enabled'), table_name='user')
    op.drop_column('user', 'is_enabled')
    # ### end Alembic commands ###
