version: '3.9'

services:
    db:
        build: ./mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: barter_nsk
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: '1234'
            MYSQL_ROOT_PASSWORD: '1234'
        volumes:
            - db-mysql:/var/lib/mysql
            - ./mysql/init:/docker-entrypoint-initdb.d
#         ports:
#             - 3361:3306

volumes:
    db-mysql:
